ktor:
  application:
    modules:
      - com.brawlpulse.api.ApplicationKt.module
  deployment:
    port: ${API_PORT}
    host: ${API_HOST}
    scheme: ${API_SCHEME}
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
